using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ParameterDrill
{
    static class StaticClass
    {
        public static void StaticMethod()
        {
            Console.WriteLine("This text is generated by the static method StaticMethod() inside the static class StaticClass");
        }
    }
}
